modLoader="javafml"
loaderVersion="[2,)"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/RedstoneControllerUnit"

[[mods]]
    modId="rsctrlunit"
    version="${mod_version}"
    displayName="RedstoneControllerUnit"
    #displayURL="https://www.curseforge.com/minecraft/mc-mods/rsctrlunit"
    logoFile="logo.png"
    authors="XFactHD"
    description=''''''

#[[mixins]]
    #config="rsctrlunit.mixins.json"

[[dependencies.rsctrlunit]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsctrlunit]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.rsctrlunit]]
    modId="atlasviewer"
    type="optional"
    versionRange="[${atlasviewer_version},)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.rsctrlunit]]
    modId="morered"
    type="optional"
    versionRange="[${morered_version},)"
    ordering="NONE"
    side="BOTH"
